// angular/src/app/components/registration-form.component.ts
import { Component, Output, EventEmitter, AfterViewInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-registration-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <form class="registration-form" [formGroup]="form" (ngSubmit)="onSubmit()">
      <div class="form-row">
        <div class="form-group">
          <label for="firstName">First Name *</label>
          <input
            type="text"
            id="firstName"
            name="firstName"
            formControlName="firstName"
            required
          />
        </div>

        <div class="form-group">
          <label for="lastName">Last Name *</label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            formControlName="lastName"
            required
          />
        </div>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="emailId">Email Address *</label>
          <input
            type="email"
            id="emailId"
            name="emailId"
            formControlName="emailId"
            required
          />
        </div>

        <div class="form-group">
          <label for="emailIdConfirmation">Confirm Email Address *</label>
          <input
            type="email"
            id="emailIdConfirmation"
            name="emailIdConfirmation"
            formControlName="emailIdConfirmation"
            required
          />
        </div>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="companyName">Company Name</label>
          <input
            type="text"
            id="companyName"
            name="companyName"
            formControlName="companyName"
          />
        </div>

        <div class="form-group">
          <label for="jobTitle">Job Title / Role</label>
          <input
            type="text"
            id="jobTitle"
            name="jobTitle"
            formControlName="jobTitle"
          />
        </div>
      </div>

      <div class="form-group">
        <label for="linkedinProfile">LinkedIn Profile URL</label>
        <input
          type="url"
          id="linkedinProfile"
          name="linkedinProfile"
          formControlName="linkedinProfile"
          placeholder="https://linkedin.com/in/yourprofile"
        />
      </div>

      <div class="form-actions">
        <button type="button" class="btn-secondary" (click)="onCancel()">
          Cancel
        </button>
        <button type="submit" class="btn-primary">
          Next
        </button>
      </div>
    </form>
  `,
})
export class RegistrationFormComponent implements AfterViewInit, OnDestroy {
  @Output() formSubmit = new EventEmitter<any>();
  @Output() formCancel = new EventEmitter<void>();

  form: FormGroup;
  private autofillPollInterval: ReturnType<typeof setInterval> | null = null;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      emailId: ['', [Validators.required, Validators.email]],
      emailIdConfirmation: ['', [Validators.required, Validators.email]],
      companyName: [''],
      jobTitle: [''],
      linkedinProfile: [''],
    });
  }

  /**
   * EXTERNAL AUTOFILL SYNC
   *
   * The Premagic LoginWidget autofills form fields by setting DOM input .value
   * directly. Angular Reactive Forms do NOT detect DOM-level value changes --
   * only changes through the FormControl API or user-dispatched input events.
   *
   * This polling mechanism checks every 500ms if any DOM input value differs
   * from its FormControl value and syncs them. It stops once all required
   * fields are filled (autofill is complete) or on component destroy.
   */
  ngAfterViewInit(): void {
    this.autofillPollInterval = setInterval(() => {
      this.syncDomValuesToForm();
    }, 500);
  }

  ngOnDestroy(): void {
    this.stopPolling();
  }

  private syncDomValuesToForm(): void {
    const controls = this.form.controls;
    let changed = false;

    Object.keys(controls).forEach((key) => {
      const input = document.getElementById(key) as HTMLInputElement | null;
      if (input && input.value !== controls[key].value) {
        controls[key].setValue(input.value, { emitEvent: false });
        changed = true;
      }
    });

    if (changed) {
      this.form.updateValueAndValidity();
    }

    // Stop polling once all required fields have been filled
    const { firstName, lastName, emailId } = this.form.controls;
    if (firstName.value && lastName.value && emailId.value) {
      this.stopPolling();
    }
  }

  private stopPolling(): void {
    if (this.autofillPollInterval) {
      clearInterval(this.autofillPollInterval);
      this.autofillPollInterval = null;
    }
  }

  onSubmit(): void {
    // Final sync before submit in case the poll hasn't caught the latest values
    this.syncDomValuesToForm();
    this.formSubmit.emit(this.form.value);
  }

  onCancel(): void {
    this.formCancel.emit();
  }
}

// vue/src/components/RegistrationForm.vue
<script setup>
import { reactive, onMounted, onUnmounted } from 'vue'

const emit = defineEmits(['submit', 'cancel'])

const FORM_FIELD_IDS = ['firstName', 'lastName', 'emailId', 'emailIdConfirmation', 'companyName', 'jobTitle', 'linkedinProfile']

const formData = reactive({
  firstName: '',
  lastName: '',
  emailId: '',
  emailIdConfirmation: '',
  companyName: '',
  jobTitle: '',
  linkedinProfile: '',
})

/**
 * EXTERNAL AUTOFILL SYNC
 *
 * The Premagic LoginWidget autofills form fields by setting DOM input .value
 * directly. Vue's v-model does NOT detect programmatic .value changes -- only
 * user-dispatched input events. This polling mechanism checks every 500ms if
 * any DOM input value differs from the reactive data and syncs them.
 */
let pollInterval = null

function syncDomToState() {
  FORM_FIELD_IDS.forEach((id) => {
    const input = document.getElementById(id)
    if (input && input.value !== formData[id]) {
      formData[id] = input.value
    }
  })

  // Stop polling once required fields are filled
  if (formData.firstName && formData.lastName && formData.emailId) {
    stopPolling()
  }
}

function stopPolling() {
  if (pollInterval) {
    clearInterval(pollInterval)
    pollInterval = null
  }
}

onMounted(() => {
  pollInterval = setInterval(syncDomToState, 500)
})

onUnmounted(() => {
  stopPolling()
})

function handleSubmit(e) {
  e.preventDefault()
  // Final sync before submit
  syncDomToState()
  emit('submit', { ...formData })
}

function handleCancel() {
  emit('cancel')
}
</script>

<template>
  <form class="registration-form" @submit="handleSubmit">
    <div class="form-row">
      <div class="form-group">
        <label for="firstName">First Name *</label>
        <input
          id="firstName"
          name="firstName"
          v-model="formData.firstName"
          type="text"
          placeholder="Enter your first name"
          required
        />
      </div>
      <div class="form-group">
        <label for="lastName">Last Name *</label>
        <input
          id="lastName"
          name="lastName"
          v-model="formData.lastName"
          type="text"
          placeholder="Enter your last name"
          required
        />
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label for="emailId">Email Address *</label>
        <input
          id="emailId"
          name="emailId"
          v-model="formData.emailId"
          type="email"
          placeholder="Enter your email address"
          required
        />
      </div>
      <div class="form-group">
        <label for="emailIdConfirmation">Confirm Email Address *</label>
        <input
          id="emailIdConfirmation"
          name="emailIdConfirmation"
          v-model="formData.emailIdConfirmation"
          type="email"
          placeholder="Confirm your email address"
          required
        />
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label for="companyName">Company Name</label>
        <input
          id="companyName"
          name="companyName"
          v-model="formData.companyName"
          type="text"
          placeholder="Enter your company name"
        />
      </div>
      <div class="form-group">
        <label for="jobTitle">Job Title</label>
        <input
          id="jobTitle"
          name="jobTitle"
          v-model="formData.jobTitle"
          type="text"
          placeholder="Enter your job title"
        />
      </div>
    </div>

    <div class="form-group">
      <label for="linkedinProfile">LinkedIn Profile</label>
      <input
        id="linkedinProfile"
        name="linkedinProfile"
        v-model="formData.linkedinProfile"
        type="url"
        placeholder="https://linkedin.com/in/your-profile"
      />
    </div>

    <div class="form-actions">
      <button type="button" class="btn-secondary" @click="handleCancel">
        Cancel
      </button>
      <button type="submit" class="btn-primary">
        Complete Registration
      </button>
    </div>
  </form>
</template>
