// vue/src/pages/RegistrationPage.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import LoginWidget from '../premagic-widgets/LoginWidget.vue'
import RegistrationForm from '../components/RegistrationForm.vue'

const router = useRouter()

const ticket = ref(null)

onMounted(() => {
  const state = history.state
  if (state && state.ticket) {
    ticket.value = state.ticket
  }
})

const premagicConfig = {
  shareId: 'AI-everything-Egypt',
  websiteId: 'ai-everything-egypt', // DEPRECATED: will be removed in Q2 2026
  domain: 'aieverything', // DEPRECATED: will be removed in Q2 2026
}

function handleSubmit(formData) {
  const registrationData = {
    ...formData,
    ticket: ticket.value,
    registeredAt: new Date().toISOString(),
  }
  sessionStorage.setItem(
    'registrationData',
    JSON.stringify(registrationData)
  )
  window.location.href = '/success'
}

function handleCancel() {
  router.push('/')
}
</script>

<template>
  <div class="registration-page">
    <div class="page-container">
      <div v-if="!ticket" class="error-message">
        <h2>No Ticket Selected</h2>
        <p>Please go back and select a ticket first.</p>
        <button @click="router.push('/')">Back to Event Page</button>
      </div>

      <template v-else>
        <div class="registration-header">
          <h1>Register for AI Everything Egypt</h1>
          <p style="color: rgba(255, 255, 255, 0.8); font-size: 1.1rem">
            {{ ticket.name }} Ticket - {{ ticket.price }} {{ ticket.currency }}
          </p>
        </div>

        <div class="registration-content">
          <LoginWidget :config="premagicConfig" />
          <RegistrationForm
            @submit="handleSubmit"
            @cancel="handleCancel"
          />
        </div>
      </template>
    </div>
  </div>
</template>

// react/src/pages/RegistrationPage.js
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import LoginWidget from '../premagic-widgets/LoginWidget';
import RegistrationForm from '../components/RegistrationForm';
import '../styles.css';

const RegistrationPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const ticket = location.state?.ticket;
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    companyName: '',
    jobTitle: '',
    emailId: '',
    emailIdConfirmation: '',
    linkedinProfile: '',
    photo: ''
  });

  // Premagic configuration
  const premagicConfig = {
    shareId: "AI-everything-Egypt",
    websiteId: "ai-everything-egypt",  // DEPRECATED: will be removed in Q2 2026
    domain: "aieverything"             // DEPRECATED: will be removed in Q2 2026
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    sessionStorage.setItem('registrationData', JSON.stringify({ ticket, formData }));
    window.location.href = '/success';
  };

  const handleCancel = () => {
    navigate('/');
  };

  if (!ticket) {
    return (
      <div className="registration-page">
        <div className="page-container">
          <div className="error-message">
            <h2>No ticket selected</h2>
            <p>Please go back and select a ticket first.</p>
            <button onClick={() => navigate('/')}>Go Back</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="registration-page">
      <div className="page-container">
        <div className="registration-header">
          <h1>Complete Your Registration</h1>
        </div>

        <div className="registration-content">
          {/* Premagic Login Widget */}
          <LoginWidget config={premagicConfig} />

          <RegistrationForm
            formData={formData}
            handleInputChange={handleInputChange}
            handleSubmit={handleSubmit}
            onCancel={handleCancel}
          />
        </div>
      </div>
    </div>
  );
};

export default RegistrationPage;
