// angular/src/app/pages/registration-page.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { LoginWidgetComponent } from '../premagic-widgets/login-widget.component';
import { RegistrationFormComponent } from '../components/registration-form.component';

@Component({
  selector: 'app-registration-page',
  standalone: true,
  imports: [CommonModule, LoginWidgetComponent, RegistrationFormComponent],
  template: `
    <!-- Error state: no ticket selected -->
    <div *ngIf="!ticket" class="registration-page">
      <div class="page-container">
        <div class="error-message">
          <h2>No ticket selected</h2>
          <p>Please go back and select a ticket first.</p>
          <button (click)="goBack()">Go Back</button>
        </div>
      </div>
    </div>

    <!-- Registration form -->
    <div *ngIf="ticket" class="registration-page">
      <div class="page-container">
        <div class="registration-header">
          <h1>Complete Your Registration</h1>
        </div>

        <div class="registration-content">
          <!-- Premagic Login Widget -->
          <app-login-widget [config]="premagicConfig"></app-login-widget>

          <app-registration-form
            (formSubmit)="onSubmit($event)"
            (formCancel)="onCancel()"
          ></app-registration-form>
        </div>
      </div>
    </div>
  `,
})
export class RegistrationPageComponent {
  ticket: any;

  premagicConfig = {
    shareId: 'AI-everything-Egypt',
    websiteId: 'ai-everything-egypt',  // DEPRECATED: will be removed in Q2 2026
    domain: 'aieverything',            // DEPRECATED: will be removed in Q2 2026
  };

  constructor(private router: Router) {
    const state = history.state;
    this.ticket = state?.ticket ?? null;
  }

  onSubmit(formData: any): void {
    sessionStorage.setItem('registrationData', JSON.stringify({ ticket: this.ticket, formData }));
    window.location.href = '/success';
  }

  onCancel(): void {
    this.router.navigate(['/']);
  }

  goBack(): void {
    this.router.navigate(['/']);
  }
}

// react/src/pages/RegistrationPage.js
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import LoginWidget from '../premagic-widgets/LoginWidget';
import RegistrationForm from '../components/RegistrationForm';
import '../styles.css';

const RegistrationPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const ticket = location.state?.ticket;
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    companyName: '',
    jobTitle: '',
    emailId: '',
    emailIdConfirmation: '',
    linkedinProfile: '',
    photo: ''
  });

  // Premagic configuration
  const premagicConfig = {
    shareId: "AI-everything-Egypt",
    websiteId: "ai-everything-egypt",  // DEPRECATED: will be removed in Q2 2026
    domain: "aieverything"             // DEPRECATED: will be removed in Q2 2026
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    sessionStorage.setItem('registrationData', JSON.stringify({ ticket, formData }));
    window.location.href = '/success';
  };

  const handleCancel = () => {
    navigate('/');
  };

  if (!ticket) {
    return (
      <div className="registration-page">
        <div className="page-container">
          <div className="error-message">
            <h2>No ticket selected</h2>
            <p>Please go back and select a ticket first.</p>
            <button onClick={() => navigate('/')}>Go Back</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="registration-page">
      <div className="page-container">
        <div className="registration-header">
          <h1>Complete Your Registration</h1>
        </div>

        <div className="registration-content">
          {/* Premagic Login Widget */}
          <LoginWidget config={premagicConfig} />

          <RegistrationForm
            formData={formData}
            handleInputChange={handleInputChange}
            handleSubmit={handleSubmit}
            onCancel={handleCancel}
          />
        </div>
      </div>
    </div>
  );
};

export default RegistrationPage;
