// vue/src/App.vue
<script setup>
import { useRoute } from 'vue-router'

const route = useRoute()
</script>

<template>
  <div class="app-container">
    <header class="main-header">
      <div class="main-header-inner">
        <router-link to="/register/select" class="main-header-brand">Premagic Demo</router-link>
        <nav class="main-header-nav">
          <router-link
            to="/register/select"
            class="main-header-nav-item"
            :class="{ active: route.path.startsWith('/register') }"
          >
            <span class="main-header-nav-label">Registration</span>
            <span class="main-header-nav-note">LoginWidget + form autofill</span>
          </router-link>
          <router-link
            to="/profile"
            class="main-header-nav-item"
            :class="{ active: route.path === '/profile' }"
          >
            <span class="main-header-nav-label">Profile</span>
            <span class="main-header-nav-note">PosterWidget with prefillData</span>
          </router-link>
        </nav>
      </div>
    </header>
    <router-view />
  </div>
</template>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app-container">
      <header class="main-header">
        <div class="main-header-inner">
          <a routerLink="/register/select" class="main-header-brand">Premagic Demo</a>
          <nav class="main-header-nav">
            <a routerLink="/register/select" routerLinkActive="active" class="main-header-nav-item">
              <span class="main-header-nav-label">Registration</span>
              <span class="main-header-nav-note">LoginWidget + form autofill</span>
            </a>
            <a routerLink="/profile" routerLinkActive="active" class="main-header-nav-item">
              <span class="main-header-nav-label">Profile</span>
              <span class="main-header-nav-note">PosterWidget with prefillData</span>
            </a>
          </nav>
        </div>
      </header>
      <router-outlet></router-outlet>
    </div>
  `,
})
export class AppComponent {}
