// vue/src/components/RegistrationForm.vue
<script setup>
import { reactive } from 'vue'

const emit = defineEmits(['submit', 'cancel'])

const formData = reactive({
  firstName: '',
  lastName: '',
  emailId: '',
  emailIdConfirmation: '',
  companyName: '',
  jobTitle: '',
  linkedinProfile: '',
})

function handleSubmit(e) {
  e.preventDefault()
  emit('submit', { ...formData })
}

function handleCancel() {
  emit('cancel')
}
</script>

<template>
  <form class="registration-form" @submit="handleSubmit">
    <div class="form-row">
      <div class="form-group">
        <label for="firstName">First Name *</label>
        <input
          id="firstName"
          v-model="formData.firstName"
          type="text"
          placeholder="Enter your first name"
          required
        />
      </div>
      <div class="form-group">
        <label for="lastName">Last Name *</label>
        <input
          id="lastName"
          v-model="formData.lastName"
          type="text"
          placeholder="Enter your last name"
          required
        />
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label for="emailId">Email Address *</label>
        <input
          id="emailId"
          v-model="formData.emailId"
          type="email"
          placeholder="Enter your email address"
          required
        />
      </div>
      <div class="form-group">
        <label for="emailIdConfirmation">Confirm Email Address *</label>
        <input
          id="emailIdConfirmation"
          v-model="formData.emailIdConfirmation"
          type="email"
          placeholder="Confirm your email address"
          required
        />
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label for="companyName">Company Name</label>
        <input
          id="companyName"
          v-model="formData.companyName"
          type="text"
          placeholder="Enter your company name"
        />
      </div>
      <div class="form-group">
        <label for="jobTitle">Job Title</label>
        <input
          id="jobTitle"
          v-model="formData.jobTitle"
          type="text"
          placeholder="Enter your job title"
        />
      </div>
    </div>

    <div class="form-group">
      <label for="linkedinProfile">LinkedIn Profile</label>
      <input
        id="linkedinProfile"
        v-model="formData.linkedinProfile"
        type="url"
        placeholder="https://linkedin.com/in/your-profile"
      />
    </div>

    <div class="form-actions">
      <button type="button" class="btn-secondary" @click="handleCancel">
        Cancel
      </button>
      <button type="submit" class="btn-primary">
        Complete Registration
      </button>
    </div>
  </form>
</template>

// react/src/components/RegistrationForm.js
import React from 'react';

/**
 * REGISTRATION FORM COMPONENT
 * 
 * Reusable registration form component that can be used in any page.
 * 
 * @param {Object} formData - Form data state
 * @param {Function} handleInputChange - Handler for input changes
 * @param {Function} handleSubmit - Handler for form submission
 * @param {Function} onCancel - Handler for cancel button
 */
const RegistrationForm = ({ formData, handleInputChange, handleSubmit, onCancel }) => {
  return (
    <form className="registration-form" onSubmit={handleSubmit}>
      <div className="form-row">
        <div className="form-group">
          <label htmlFor="firstName">First Name *</label>
          <input
            type="text"
            id="firstName"
            name="firstName"
            value={formData.firstName}
            onChange={handleInputChange}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="lastName">Last Name *</label>
          <input
            type="text"
            id="lastName"
            name="lastName"
            value={formData.lastName}
            onChange={handleInputChange}
            required
          />
        </div>
      </div>

      <div className="form-row">
        <div className="form-group">
          <label htmlFor="emailId">Email Address *</label>
          <input
            type="email"
            id="emailId"
            name="emailId"
            value={formData.emailId}
            onChange={handleInputChange}
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="emailIdConfirmation">Confirm Email Address *</label>
          <input
            type="email"
            id="emailIdConfirmation"
            name="emailIdConfirmation"
            value={formData.emailIdConfirmation}
            onChange={handleInputChange}
            required
          />
        </div>
      </div>
      <div className="form-row">
        <div className="form-group">
          <label htmlFor="companyName">Company Name</label>
          <input
            type="text"
            id="companyName"
            name="companyName"
            value={formData.companyName}
            onChange={handleInputChange}
          />
        </div>

        <div className="form-group">
          <label htmlFor="jobTitle">Job Title / Role</label>
          <input
            type="text"
            id="jobTitle"
            name="jobTitle"
            value={formData.jobTitle}
            onChange={handleInputChange}
          />
        </div>
      </div>

      <div className="form-group">
        <label htmlFor="linkedinProfile">LinkedIn Profile URL</label>
        <input
          type="url"
          id="linkedinProfile"
          name="linkedinProfile"
          value={formData.linkedinProfile}
          onChange={handleInputChange}
          placeholder="https://linkedin.com/in/yourprofile"
        />
      </div>
      <div className="form-actions">
        <button type="button" className="btn-secondary" onClick={onCancel}>
          Cancel
        </button>
        <button type="submit" className="btn-primary">
          Next
        </button>
      </div>
    </form>
  );
};

export default RegistrationForm;
